### ISSUE TITLE
Different results for versions with trailing zeros and different lengths

### ISSUE THREAD

**Issue by mpak** [stijnster/NSString-compareToVersion#2]
I don't use this category personally, just got here from StackOverflow
Since you are "appending" zeros for second string only, there is some inconsistency in comparison:
[@"1.2.0" compareToVersion:@"1.2"] == NSOrderedSame
but
[@"1.2" compareToVersion:@"1.2.0"] == NSOrderedAscending

**Comment by stijnster** [comment]
Thanks for pointing that out, it makes sense. I'll have a look at it in the upcoming days and keep you posted.

Thanks again!

Stijn
